# Generated by Django 5.2.10 on 2026-01-14 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimeWindow',
        ),
    ]
